API_KEY = "YtIdWcK8HGBsGTWqegcWOS2P0"
API_SECRECT = "m8iJqjLJ8G4tnoaOfXKbcMVZVVacQ96AuzVzPy29uF4LFVwh4s"
BEARER_TOKEN = "AAAAAAAAAAAAAAAAAAAAAB7FhgEAAAAAxr50NviA1In5hvJz48RiJwYi7aM%3DjgEh8TzfcwwWmI5A7yJrEMrD3bbjgczzvWMkG2r6ADCaxrh5dr"
DISCORD_TOKEN = "MTAyNTczMjExNTczNzg4MjY3NA.GTvW9T.AgFHevXXR2bAKggyRHd3zysMvTmpW6xXLH88yA"
account_list = ["POTUS","AndrzejDuda","ZelenskyyUa","unknown__polish"]
